version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "America/Los_Angeles"
    groups:
      npm:
        patterns:
          - "*"
