name: Check

on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Run checks
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install NPM dependencies
        run: npm install

      - name: Check Astro
        run: npm run astro check --minimumFailingSeverity warning

      - name: Build Astro
        run: npm run build
