name: Publish

on:
  push:
    branches:
      - main
      - preview

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install NPM dependencies
        run: npm install

      - name: Check Astro
        run: npm run astro check --minimumFailingSeverity warning

      - name: Check Prettier
        run: npm run prettier-check

      - name: Build Astro
        run: npm run build

      - name: Publish to git-pages (staging)
        run: |
          tar -C dist --zstd -cf - . | curl -X PUT 'https://staging.brioche.dev' -H "Authorization: Pages $GIT_PAGES_PASSWORD_STAGING_BRIOCHE_DEV" -H 'Content-Type: application/x-tar+zstd' --data-binary @-
        env:
          GIT_PAGES_PASSWORD_STAGING_BRIOCHE_DEV: ${{ secrets.GIT_PAGES_PASSWORD_STAGING_BRIOCHE_DEV }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
